shared:
  image: node:16

jobs:
  test:
    requires: [~pr, ~commit]
    steps:
      - metaset: meta set hello "Hello"
  show-meta:
    requires: [test]
    steps:
      - if [ "$(meta get hello)" != "TEST" ]; then exit 1; fi;
